"""
AI-Based Academic Journal Recommendation Assistant
PDF Report Generation Module using ReportLab.
"""

from datetime import datetime
import os
import tempfile
from typing import Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and render total page count and professional headers/footers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(40, 755, "AI Academic Journal Recommendation Dossier")
            self.drawRightString(572, 755, "Multi-Agent Scholarly Evaluation")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(40, 750, 572, 750)

        # Footer (all pages)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(40, 45, 572, 45)

        footer_text = "Generated by AI Journal Recommender (LangGraph • OpenAlex • DOAJ • Crossref)"
        self.drawString(40, 32, footer_text)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(572, 32, page_str)

        self.restoreState()


def generate_recommendation_pdf(
    state_result: dict[str, Any],
    output_path: str | None = None,
) -> str:
    """
    Generates a professional academic PDF dossier report from recommendation state data.

    :param state_result: Complete state dict returned by the LangGraph recommendation pipeline.
    :param output_path: Optional output file path. If None, saves to a temporary file.
    :return: Absolute file path to the generated PDF.
    """
    if output_path is None:
        temp_dir = os.path.join(tempfile.gettempdir(), "journal_ai_reports")
        os.makedirs(temp_dir, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = os.path.join(temp_dir, f"Journal_Recommendation_Report_{timestamp}.pdf")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=50,
        bottomMargin=55,
    )

    styles = getSampleStyleSheet()

    # Custom Color Palette
    PRIMARY_COLOR = colors.HexColor("#1E3A8A")  # Deep Navy
    SECONDARY_COLOR = colors.HexColor("#2563EB")  # Royal Blue
    ACCENT_DARK = colors.HexColor("#0F172A")
    TEXT_MUTED = colors.HexColor("#475569")
    BG_LIGHT = colors.HexColor("#F8FAFC")
    BORDER_LIGHT = colors.HexColor("#E2E8F0")

    # Typography Styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=PRIMARY_COLOR,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=TEXT_MUTED,
        spaceAfter=12,
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=PRIMARY_COLOR,
        spaceBefore=14,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=ACCENT_DARK,
    )
    body_bold = ParagraphStyle(
        "DocBodyBold",
        parent=body_style,
        fontName="Helvetica-Bold",
    )
    desc_style = ParagraphStyle(
        "DescBody",
        parent=body_style,
        fontName="Helvetica-Oblique",
        textColor=colors.HexColor("#1E293B"),
        leading=13,
    )
    journal_title_style = ParagraphStyle(
        "JournalTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=PRIMARY_COLOR,
    )
    table_cell = ParagraphStyle(
        "TableCell",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=ACCENT_DARK,
    )
    table_cell_bold = ParagraphStyle(
        "TableCellBold",
        parent=table_cell,
        fontName="Helvetica-Bold",
    )
    table_header = ParagraphStyle(
        "TableHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=colors.white,
    )
    bullet_style = ParagraphStyle(
        "DocBullet",
        parent=body_style,
        leftIndent=12,
        firstLineIndent=-8,
        spaceAfter=3,
    )

    story = []

    profile = state_result.get("paper_profile", {})
    recs = state_result.get("recommendations", [])
    conflicts = state_result.get("conflicts", [])

    # 1. Header Banner
    story.append(Paragraph("AI Academic Journal Recommendation Dossier", title_style))
    date_str = datetime.now().strftime("%B %d, %Y • %H:%M UTC")
    story.append(
        Paragraph(
            f"Multi-Agent Evaluation • Scope Gating & MCDA Ranking • Generated on {date_str}",
            subtitle_style,
        )
    )
    story.append(HRFlowable(width="100%", thickness=1.5, color=SECONDARY_COLOR, spaceAfter=12))

    # 2. Manuscript Profile Card
    story.append(Paragraph("📄 Evaluated Manuscript Profile", section_heading))

    manuscript_title = profile.get("title", "Submitted Manuscript")
    domain = profile.get("domain", "Academic Research")
    methodology = profile.get("methodology", "Empirical Evaluation")
    keywords = ", ".join(str(k) for k in profile.get("keywords", [])[:8]) or "N/A"
    queries = ", ".join(profile.get("academic_search_queries", [])[:3]) or "N/A"

    profile_data = [
        [
            Paragraph("<b>Manuscript Title:</b>", table_cell_bold),
            Paragraph(f"<i>{manuscript_title}</i>", table_cell),
        ],
        [
            Paragraph("<b>Primary Field / Domain:</b>", table_cell_bold),
            Paragraph(domain, table_cell),
        ],
        [
            Paragraph("<b>Core Methodology:</b>", table_cell_bold),
            Paragraph(methodology, table_cell),
        ],
        [
            Paragraph("<b>Key Concepts & Keywords:</b>", table_cell_bold),
            Paragraph(keywords, table_cell),
        ],
        [
            Paragraph("<b>Target Search Formulations:</b>", table_cell_bold),
            Paragraph(queries, table_cell),
        ],
    ]

    profile_table = Table(profile_data, colWidths=[140, 392])
    profile_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    story.append(profile_table)
    story.append(Spacer(1, 12))

    # 3. Top Recommended Venues Summary Table
    story.append(Paragraph("🏆 Recommended Venues Leaderboard", section_heading))

    table_data = [
        [
            Paragraph("Rank", table_header),
            Paragraph("Journal Name", table_header),
            Paragraph("Publisher", table_header),
            Paragraph("Match %", table_header),
            Paragraph("Access Model", table_header),
            Paragraph("Author Fee (APC)", table_header),
        ]
    ]

    for item in recs:
        rank = item.get("rank", 1)
        name = item.get("journal", "Unknown")
        pub = item.get("publisher", "Academic Publisher")
        score = item.get("score", 0)
        apc = item.get("apc_usd")
        apc_str = "$0 (Diamond OA)" if apc == 0 else (f"~${apc} USD" if apc else "Subscription / Free Track")
        oa_str = "Open Access (DOAJ)" if item.get("is_in_doaj") else ("Open Access" if item.get("is_oa") else "Hybrid / Sub.")

        table_data.append([
            Paragraph(f"<b>#{rank}</b>", table_cell),
            Paragraph(f"<b>{name}</b>", table_cell),
            Paragraph(pub, table_cell),
            Paragraph(f"<b>{score}%</b>", table_cell_bold),
            Paragraph(oa_str, table_cell),
            Paragraph(apc_str, table_cell),
        ])

    summary_table = Table(table_data, colWidths=[35, 175, 110, 52, 80, 80])
    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG_LIGHT]),
            ("BOX", (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ])
    )
    story.append(summary_table)
    story.append(Spacer(1, 14))

    # 4. Detailed Dossier & Descriptions for Each Journal
    story.append(Paragraph("🔍 Detailed Journal Submission Dossiers & Aims/Scope", section_heading))

    for item in recs:
        rank = item.get("rank", 1)
        name = item.get("journal", "Unknown Journal")
        score = item.get("score", 0)
        publisher = item.get("publisher", "Academic Publisher")
        issn = item.get("issn", "N/A")
        scores = item.get("agent_scores", {})
        explanation = item.get("explanation", {})
        description = item.get("description", "")
        recent_works = item.get("recent_works", [])

        badges = []
        if item.get("is_in_doaj"):
            badges.append("DOAJ Indexed")
        if item.get("is_oa"):
            badges.append("Open Access")
        if item.get("apc_usd") == 0:
            badges.append("Diamond OA ($0 Fee)")
        elif item.get("apc_usd"):
            badges.append(f"APC: ~${item.get('apc_usd')} USD")
        badge_line = " • ".join(badges) if badges else "Standard Indexing"

        card_elements = []

        # Journal Title & Header Line
        header_text = f"<b>#{rank}. {name}</b> &nbsp;&nbsp;[Composite Match: <b>{score}%</b>]"
        card_elements.append(Paragraph(header_text, journal_title_style))
        card_elements.append(
            Paragraph(f"<i>Publisher:</i> {publisher} &nbsp;|&nbsp; <i>ISSN:</i> {issn} &nbsp;|&nbsp; {badge_line}", subtitle_style)
        )

        # Agent Breakdown Bar
        breakdown_text = (
            f"<b>Agent Breakdown:</b> Scope Fit: <b>{scores.get('scope', 0)}%</b> | "
            f"RAG Vector: <b>{scores.get('similarity', 0)}%</b> | "
            f"Credibility: <b>{scores.get('credibility', 0)}%</b> | "
            f"Cost: <b>{scores.get('cost', 0)}%</b> | "
            f"Prestige: <b>{scores.get('impact', 0)}%</b> | "
            f"Turnaround: <b>{scores.get('turnaround', 0)}%</b>"
        )
        card_elements.append(Paragraph(breakdown_text, body_style))
        card_elements.append(Spacer(1, 4))

        # 4a. Journal Description & Aims/Scope
        if description:
            card_elements.append(Paragraph("<b>📖 Journal Description & Scope:</b>", body_bold))
            card_elements.append(Paragraph(description, desc_style))
            card_elements.append(Spacer(1, 4))

        # 4b. Why Recommended
        why_rec = explanation.get("why_recommended")
        if why_rec:
            card_elements.append(Paragraph("<b>💡 Why Recommended:</b>", body_bold))
            card_elements.append(Paragraph(why_rec, body_style))
            card_elements.append(Spacer(1, 4))

        # 4c. Key Strengths
        strengths = explanation.get("strengths", [])
        if strengths:
            card_elements.append(Paragraph("<b>⭐ Key Strengths:</b>", body_bold))
            for s in strengths:
                card_elements.append(Paragraph(f"• {s}", bullet_style))

        # 4d. Caveats & Review Considerations
        caveats = explanation.get("caveats", [])
        if caveats:
            card_elements.append(Paragraph("<b>⚠️ Trade-offs & Review Considerations:</b>", body_bold))
            for c in caveats:
                card_elements.append(Paragraph(f"• {c}", bullet_style))

        # 4e. Submission Strategy
        tailoring = explanation.get("tailoring_advice", [])
        if tailoring:
            card_elements.append(Paragraph("<b>✍️ Manuscript Tailoring Strategy:</b>", body_bold))
            for tip in tailoring:
                card_elements.append(Paragraph(f"• {tip}", bullet_style))

        # 4f. Recent Works
        if recent_works:
            card_elements.append(Paragraph("<b>📚 Verified Recent Publications:</b>", body_bold))
            for rw in recent_works[:2]:
                rw_title = rw.get("title", "")
                rw_doi = rw.get("doi", "")
                doi_str = f" (DOI: {rw_doi})" if rw_doi else ""
                card_elements.append(Paragraph(f"• <i>{rw_title}</i>{doi_str}", bullet_style))

        card_elements.append(Spacer(1, 8))
        card_elements.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_LIGHT, spaceAfter=8))

        story.append(KeepTogether(card_elements))

    # 5. Multi-Criteria Trade-offs & Conflict Resolutions
    conflict_elements = []
    conflict_elements.append(Paragraph("⚖️ Multi-Criteria Trade-off & Conflict Analysis", section_heading))
    if conflicts:
        for c in conflicts:
            j_name = c.get("journal", "Unknown Journal")
            spread = c.get("spread", 0)
            conflict_elements.append(Paragraph(f"<b>• {j_name}</b> (Metric Spread: {spread} pts)", body_bold))
            for to in c.get("tradeoffs", []):
                conflict_elements.append(Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;<i>Trade-off:</i> {to}", body_style))
            conflict_elements.append(
                Paragraph(f"&nbsp;&nbsp;&nbsp;&nbsp;<i>Arbitration Rationale:</i> {c.get('resolution')}", body_style)
            )
            conflict_elements.append(Spacer(1, 4))
    else:
        conflict_elements.append(
            Paragraph("✅ No major multi-criteria conflicts detected across evaluated decision dimensions.", body_style)
        )

    story.append(KeepTogether(conflict_elements))

    # Build PDF using NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path
